name: Selenium Tests with Allure & HTML Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Allure
        uses: actions/setup-allure@v1
        with:
          allure-version: 2.34.1

      - name: Run Selenium tests
        run: |
          mkdir -p reports/allure-results
          python run_all_tests.py

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/report.html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Add report summary
        if: always()
        run: |
          echo "### ✅ Selenium Tests Completed!" >> $GITHUB_STEP_SUMMARY
          echo "- 🧾 [HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Allure Report is available in artifacts." >> $GITHUB_STEP_SUMMARY
          echo "- 📸 Screenshots are attached as artifacts." >> $GITHUB_STEP_SUMMARY
